### ISSUE TITLE
free_result / Memory issues?

### ISSUE THREAD

**Issue by BHare1985** [stefangabos/Zebra_Database#75]
Recently I've been having memory issues where PHP processes are consuming upwards of 300MB each after days of uptime. It may be my code but php-fpm is full of errors relating to `free_result` which seems like it's needed for cleaning up resources. I do believe that my MySQL instance is dying unexpectedly (and I plan on fixing that) and that is why the exception is being thrown, but seems like Zebra is not cleaning up the resource if it dies?

php7.3-fpm.log:

```
[21-Dec-2022 18:16:03] WARNING: [pool www] child 14223 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Exception in /var/www/files/lib/Zebra_Database/Zebra_Database.php:4877"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 14223 said into stderr: "Stack trace:"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 14223 said into stderr: "#0 /var/www/files/lib/Zebra_Database/Zebra_Database.php(4174): Zebra_Database->_log('errors', Array)"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 14223 said into stderr: "#1 /var/www/files/lib/Zebra_Database/Zebra_Database.php(1677): Zebra_Database->_connected()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 14223 said into stderr: "#2 /var/www/files/lib/Zebra_Database/Zebra_Database.php(5156): Zebra_Database->free_result()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 14223 said into stderr: "#3 [internal function]: Zebra_Database->__destruct()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 14223 said into stderr: "#4 {main}"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 14223 said into stderr: "  thrown in /var/www/files/lib/Zebra_Database/Zebra_Database.php on line 4877"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13061 said into stderr: "NOTICE: PHP message: PHP Warning:  mysqli_error(): invalid object or resource mysqli"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13061 said into stderr: " in /var/www/files/lib/Zebra_Database/Zebra_Database.php on line 1271"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13061 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Exception in /var/www/files/lib/Zebra_Database/Zebra_Database.php:4877"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13061 said into stderr: "Stack trace:"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13061 said into stderr: "#0 /var/www/files/lib/Zebra_Database/Zebra_Database.php(4174): Zebra_Database->_log('errors', Array)"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13061 said into stderr: "#1 /var/www/files/lib/Zebra_Database/Zebra_Database.php(1677): Zebra_Database->_connected()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13061 said into stderr: "#2 /var/www/files/lib/Zebra_Database/Zebra_Database.php(5156): Zebra_Database->free_result()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13061 said into stderr: "#3 [internal function]: Zebra_Database->__destruct()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13061 said into stderr: "#4 {main}"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13061 said into stderr: "  thrown in /var/www/files/lib/Zebra_Database/Zebra_Database.php on line 4877"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12944 said into stderr: "NOTICE: PHP message: PHP Warning:  mysqli_error(): invalid object or resource mysqli"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12944 said into stderr: " in /var/www/files/lib/Zebra_Database/Zebra_Database.php on line 1271"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12944 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Exception in /var/www/files/lib/Zebra_Database/Zebra_Database.php:4877"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12944 said into stderr: "Stack trace:"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12944 said into stderr: "#0 /var/www/files/lib/Zebra_Database/Zebra_Database.php(4174): Zebra_Database->_log('errors', Array)"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12944 said into stderr: "#1 /var/www/files/lib/Zebra_Database/Zebra_Database.php(1677): Zebra_Database->_connected()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12944 said into stderr: "#2 /var/www/files/lib/Zebra_Database/Zebra_Database.php(5156): Zebra_Database->free_result()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12944 said into stderr: "#3 [internal function]: Zebra_Database->__destruct()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12944 said into stderr: "#4 {main}"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12944 said into stderr: "  thrown in /var/www/files/lib/Zebra_Database/Zebra_Database.php on line 4877"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13698 said into stderr: "NOTICE: PHP message: PHP Warning:  mysqli_error(): invalid object or resource mysqli"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13698 said into stderr: " in /var/www/files/lib/Zebra_Database/Zebra_Database.php on line 1271"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13698 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Exception in /var/www/files/lib/Zebra_Database/Zebra_Database.php:4877"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13698 said into stderr: "Stack trace:"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13698 said into stderr: "#0 /var/www/files/lib/Zebra_Database/Zebra_Database.php(4174): Zebra_Database->_log('errors', Array)"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13698 said into stderr: "#1 /var/www/files/lib/Zebra_Database/Zebra_Database.php(1677): Zebra_Database->_connected()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13698 said into stderr: "#2 /var/www/files/lib/Zebra_Database/Zebra_Database.php(5156): Zebra_Database->free_result()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13698 said into stderr: "#3 [internal function]: Zebra_Database->__destruct()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13698 said into stderr: "#4 {main}"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13698 said into stderr: "  thrown in /var/www/files/lib/Zebra_Database/Zebra_Database.php on line 4877"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12926 said into stderr: "NOTICE: PHP message: PHP Warning:  mysqli_error(): invalid object or resource mysqli"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12926 said into stderr: " in /var/www/files/lib/Zebra_Database/Zebra_Database.php on line 1271"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12926 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Exception in /var/www/files/lib/Zebra_Database/Zebra_Database.php:4877"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12926 said into stderr: "Stack trace:"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12926 said into stderr: "#0 /var/www/files/lib/Zebra_Database/Zebra_Database.php(4174): Zebra_Database->_log('errors', Array)"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12926 said into stderr: "#1 /var/www/files/lib/Zebra_Database/Zebra_Database.php(1677): Zebra_Database->_connected()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12926 said into stderr: "#2 /var/www/files/lib/Zebra_Database/Zebra_Database.php(5156): Zebra_Database->free_result()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12926 said into stderr: "#3 [internal function]: Zebra_Database->__destruct()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12926 said into stderr: "#4 {main}"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 12926 said into stderr: "  thrown in /var/www/files/lib/Zebra_Database/Zebra_Database.php on line 4877"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13623 said into stderr: "NOTICE: PHP message: PHP Warning:  mysqli_error(): invalid object or resource mysqli"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13623 said into stderr: " in /var/www/files/lib/Zebra_Database/Zebra_Database.php on line 1271"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13623 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Exception in /var/www/files/lib/Zebra_Database/Zebra_Database.php:4877"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13623 said into stderr: "Stack trace:"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13623 said into stderr: "#0 /var/www/files/lib/Zebra_Database/Zebra_Database.php(4174): Zebra_Database->_log('errors', Array)"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13623 said into stderr: "#1 /var/www/files/lib/Zebra_Database/Zebra_Database.php(1677): Zebra_Database->_connected()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13623 said into stderr: "#2 /var/www/files/lib/Zebra_Database/Zebra_Database.php(5156): Zebra_Database->free_result()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13623 said into stderr: "#3 [internal function]: Zebra_Database->__destruct()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13623 said into stderr: "#4 {main}"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13623 said into stderr: "  thrown in /var/www/files/lib/Zebra_Database/Zebra_Database.php on line 4877"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13291 said into stderr: "NOTICE: PHP message: PHP Warning:  mysqli_error(): invalid object or resource mysqli"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13291 said into stderr: " in /var/www/files/lib/Zebra_Database/Zebra_Database.php on line 1271"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13291 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Exception in /var/www/files/lib/Zebra_Database/Zebra_Database.php:4877"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13291 said into stderr: "Stack trace:"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13291 said into stderr: "#0 /var/www/files/lib/Zebra_Database/Zebra_Database.php(4174): Zebra_Database->_log('errors', Array)"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13291 said into stderr: "#1 /var/www/files/lib/Zebra_Database/Zebra_Database.php(1677): Zebra_Database->_connected()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13291 said into stderr: "#2 /var/www/files/lib/Zebra_Database/Zebra_Database.php(5156): Zebra_Database->free_result()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13291 said into stderr: "#3 [internal function]: Zebra_Database->__destruct()"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13291 said into stderr: "#4 {main}"
[21-Dec-2022 18:16:03] WARNING: [pool www] child 13291 said into stderr: "  thrown in /var/www/files/lib/Zebra_Database/Zebra_Database.php on line 4877"
```

**Comment by stefangabos** [comment]
What version are you using? I am trying to figure out what is there at line 1271 but in 2.10.2 I have some comments at 1271. 
But it is weird because from your logs it looks like it is trying to `log` but then it checks if there is a `connection` which it shouldn't from withing the logging process. 

Can you please try with the latest version and if the error is still happening post the error log?

Thanks!

**Comment by stefangabos** [comment]
I've done some updates that may also have fixed your issue. 
If you can please download the latest (not a release yet) and try and see if your errors have now disappeared.
Thanks!

**Comment by stefangabos** [comment]
It's not a memory issue but an issue that is happening in PHP 8

**Comment by BHare1985** [comment]
Sorry, this was my problem. I replaced the `die()`  with throwing an exception in the `_log` function at some point and forgot about it. Once I reverted back to the original source I did not see this error anymore
